name: Newman API Test CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman
             npm install -g newman-reporter-html

      - name: Run API tests with Newman
        run: |
          newman run \
            "collection.json" \
            -e "environment.json" \
            -r cli,html \
            --reporter-html-export newman-report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: newman-report.html
        if: always()
  
        
